# Site settings
url: http://mdoninger.github.com
title: Manuel Doninger
tagline: Java and everything else
subtitle: Java and everything else

email : manuel.doninger@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.mdoninger.de" # the base hostname & protocol for your site

author :
  name : Manuel Doninger
  email : manuel.doninger@gmail.com
  github : mdoninger
  feedburner : manueldoninger

github_username:  mdoninger

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title.html

tags_path : /tags.html
archive_path: /blog/index.html

comments :
    provider : disqus
    disqus :
      short_name : manueldoninger

sharing :
    provider : custom
    googleplus: true
    twitter: true
    facebook: true